### ISSUE TITLE
config配置文件中的小数问题

### ISSUE THREAD

**Issue by chxpu** [youareeverysingleday/pyRoutingAlgorithm#1]
感谢你的代码，有一个问题需要请教，
当config配置文件中的链路成本出现小数时，程序错误，
3
x
y
z
3
x y 10.1
x z 5.1
y z 2.1

应该如何修改程序，解决这个问题？谢谢

**Comment by youareeverysingleday** [comment]
such as problem, u must recompose program's structure, because this program use list complete path weight.  so your requirement is very difficult. ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月30日(星期五) 晚上6:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[youareeverysingleday/pyRoutingAlgorithm] config配置文件中的小数问题 (#1)

**Comment by chxpu** [comment]
Thank you very much for your reply, I will try to solve the problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youareeverysingleday/pyRoutingAlgorithm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 晚上10:50
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [youareeverysingleday/pyRoutingAlgorithm] config配置文件中的小数问题 (#1)





 such as problem, u must recompose program's structure, because this program use list complete path weight.  so your requirement is very difficult. ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 ***@***.***&amp;gt; 
 发送时间:&amp;nbsp;2021年7月30日(星期五) 晚上6:08 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[youareeverysingleday/pyRoutingAlgorithm] config配置文件中的小数问题 (#1)
